---
# tasks file for zabbix
- name: Create {{ instance }} namespace
  k8s:
    name: "{{ instance }}"
    api_version: v1
    kind: Namespace
    state: "{{ state }}"

- name: Create {{ instance }} configmap
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ instance }}-configmap"
        namespace: "{{ instance }}"
      data:
        zabbix_server.conf: "{{ zabbix_server_conf}}"

- name: Create {{ instance }} postgres secret
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: zabbix-postgres
        namespace: "{{ instance }}"
      type: Opaque
      data:
        POSTGRES_PASSWORD: "{{ base64_postgres_password }}"

- name: Create {{ instance }} zabbix web services
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: zabbix-web
        namespace: "{{ instance }}"
        labels:
          app: zabbix-web
      spec:
        type: NodePort
        selector:
          app: zabbix-web
        ports:
          - targetPort: 8443
            name: frontend-https
            port: 443
          - targetPort: 8080
            name: frontend-http
            port: 80

- name: Create {{ instance }} zabbix postgres service
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: postgres-server
        namespace: "{{ instance }}"
        labels:
          app: postgres-server
      spec:
        type: NodePort
        selector:
          app: postgres-server
        ports:
          - protocol: TCP
            targetPort: 5432
            name: database
            port: 5432

- name: Create {{ instance }} zabbix data service
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: zabbix-server
        namespace: "{{ instance }}"
        labels:
          app: zabbix-server
      spec:
        type: NodePort
        selector:
          app: zabbix-server
        ports:
          - protocol: TCP
            targetPort: 10051
            name: active
            port: 10051
          - protocol: TCP
            targetPort: 10050
            name: passive
            port: 10050
          - protocol: UDP
            targetPort: 1162
            port: 162
            name: snmp-trap

- name: Create {{ instance }} zabbix agent service
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: zabbix-agent
        namespace: "{{ instance }}"
        labels:
          app: zabbix-agent
      spec:
        type: NodePort
        selector:
          app: zabbix-agent
        ports:
          - protocol: TCP
            targetPort: 10051
            name: active
            port: 10051
          - protocol: TCP
            targetPort: 10050
            name: passive
            port: 10050

- name: Create {{ instance }} postgres statefulset
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        labels:
          app: postgres-server
          release: "{{ release }}"
        name: postgres-server
        namespace: "{{ instance }}"
      spec:
        replicas: 1
        serviceName:
        selector:
          matchLabels:
            app: postgres-server
            release: "{{ release }}"
        template:
          metadata:
            labels:
              app: postgres-server
              release: "{{ release }}"
          spec:
            containers:
              - name: postgres-server
                imagePullPolicy: IfNotPresent
                image: "{{ database_image }}"
                ports:
                  - containerPort: 5432
                    name: 5432tcp5432
                    protocol: TCP
                env:
                  - name: POSTGRES_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        key: POSTGRES_PASSWORD
                        name: zabbix-postgres
                        optional: false

- name: Create {{ instance }} zabbix-server deployment
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        labels:
          app: zabbix-server
          release: "{{ release }}"
        name: zabbix-server
        namespace: "{{ instance }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: zabbix-server
            release: "{{ release }}"
        template:
          metadata:
            labels:
              app: zabbix-server
              release: "{{ release }}"
          spec:
            containers:
              - name: zabbix-server
                imagePullPolicy: IfNotPresent
                image: zabbix/zabbix-server-pgsql:alpine-trunk
                ports:
                  - containerPort: 10051
                    name: 10051tcp100510
                    protocol: TCP
                  - containerPort: 10050
                    name: 10050tcp10050
                    protocol: TCP
                env:
                  - name: "DB_SERVER_HOST"
                    value: postgres-server

- name: Create {{ instance }} zabbix-web deployment
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        labels:
          app: zabbix-web
          release: "{{ release }}"
        name: zabbix-web
        namespace: "{{ instance }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: zabbix-web
            release: "{{ release }}"
        template:
          metadata:
            labels:
              app: zabbix-web
              release: "{{ release }}"
          spec:
            containers:
              - name: zabbix-web
                imagePullPolicy: IfNotPresent
                image: zabbix/zabbix-web-nginx-pgsql:alpine-trunk
                ports:
                  - containerPort: 80
                    name: http
                    protocol: TCP
                  - containerPort: 443
                    name: https
                    protocol: TCP
                env:
                  - name: ZBX_SERVER_HOST
                    value: zabbix-server
                  - name: DB_SERVER_HOST
                    value: postgres-server
                  - name: POSTGRES_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        key: POSTGRES_PASSWORD
                        name: zabbix-postgres
                        optional: false

- name: Create {{ instance }} zabbix-agent deployment
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        labels:
          app: zabbix-agent
          release: "{{ release }}"
        name: zabbix-agent
        namespace: "{{ instance }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: zabbix-agent
            release: "{{ release }}"
        template:
          metadata:
            labels:
              app: zabbix-agent
              release: "{{ release }}"
          spec:
            containers:
              - name: zabbix-agent
                image: zabbix/zabbix-agent:alpine-trunk
                imagePullPolicy: IfNotPresent