---
# tasks file for zabbix
- name: Ensure namespace {{ instance }} {{ state }}
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ instance }}"
        labels:
          app: zabbix
          release: "{{ release }}"
          domain: "{{ domain }}"

- name: Ensure zabbix-postgres secret {{ state }} in namespace {{ instance }}
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: zabbix-postgres
        namespace: "{{ instance }}"
        labels:
          app: postgres
          tier: database
          release: "{{ release }}"
          domain: "{{ domain }}"
      type: Opaque
      data:
        POSTGRES_PASSWORD: "{{ base64_postgres_password }}"

- name: Ensure postgres-server service {{ state }} in namespace {{ instance }}
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: postgres-server
        namespace: "{{ instance }}"
        labels:
          app: postgres
          tier: database
          release: "{{ release }}"
          domain: "{{ domain }}"
      spec:
        selector:
          app: postgres
          tier: database
          release: "{{ release }}"
          domain: "{{ domain }}"
        ports:
          - targetPort: 5432
            name: database
            port: 5432
            protocol: TCP

- name: Ensure zabbix-server service {{ state }} in namespace {{ instance }}
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: zabbix-server
        namespace: "{{ instance }}"
        labels:
          app: zabbix
          tier: server
          release: "{{ release }}"
          domain: "{{ domain }}"
      spec:
        type: NodePort
        selector:
          app: zabbix
          tier: server
          release: "{{ release }}"
          domain: "{{ domain }}"
        ports:
          - targetPort: 10051
            name: active
            port: 10051
            protocol: TCP
          - targetPort: 10050
            name: agent-passive
            port: 10050
            protocol: TCP
          - targetPort: 1162
            port: 162
            name: snmp-trap
            protocol: UDP

- name: Ensure zabbix-web services {{ state }} in namespace {{ instance }}
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: zabbix-web
        namespace: "{{ instance }}"
        labels:
          app: zabbix
          tier: web
          release: "{{ release }}"
          domain: "{{ domain }}"
      spec:
        type: NodePort
        selector:
          app: zabbix
          tier: web
          release: "{{ release }}"
          domain: "{{ domain }}"
        ports:
          - targetPort: 8443
            name: frontend-https
            port: 443
          - targetPort: 8080
            name: frontend-http
            port: 80

- name: Ensure postgres-server statefulset {{ state }} in namespace {{ instance }}
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        labels:
          app: postgres
          tier: database
          release: "{{ release }}"
          domain: "{{ domain }}"
        name: postgres-server
        namespace: "{{ instance }}"
      spec:
        replicas: 1
        serviceName:
        selector:
          matchLabels:
            app: postgres
            tier: database
            release: "{{ release }}"
            domain: "{{ domain }}"
        template:
          metadata:
            labels:
              app: postgres
              tier: database
              release: "{{ release }}"
              domain: "{{ domain }}"
          spec:
            containers:
              - name: postgres-server
                imagePullPolicy: "{{ database_image_pull_policy | default(image_pull_policy) }}"
                image: "{{ database_image }}:{{ database_image_tag }}"
                ports:
                  - containerPort: 5432
                    name: database
                    protocol: TCP
                env:
                  - name: POSTGRES_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        key: POSTGRES_PASSWORD
                        name: zabbix-postgres
                        optional: false
                  - name: PGDATA
                    value: /var/lib/postgresql/data
                volumeMounts:
                  - name: postgres-data
                    mountPath: /var/lib/postgresql/data
        volumeClaimTemplates:
          - metadata:
              name: postgres-data
              labels:
                app: postgres
                tier: database
                release: "{{ release }}"
                domain: "{{ domain }}"
            spec:
              accessModes:
                - ReadWriteMany
              selector:
                matchLabels:
                  app: postgres
                  tier: database
                  release: "{{ release }}"
                  domain: "{{ domain }}"
              resources:
                requests:
                  storage: "{{ database_claim_size }}"

- name: Ensure zabbix-server deployment {{ state }} in namespace {{ instance }}
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        labels:
          app: zabbix
          tier: server
          release: "{{ release }}"
          domain: "{{ domain }}"
        name: zabbix-server
        namespace: "{{ instance }}"
      spec:
        replicas: "{{ zabbix_server_replicas }}"
        selector:
          matchLabels:
            app: zabbix
            tier: server
            release: "{{ release }}"
            domain: "{{ domain }}"
        template:
          metadata:
            labels:
              app: zabbix
              tier: server
              release: "{{ release }}"
              domain: "{{ domain }}"
          spec:
            containers:
              - name: zabbix-server
                image: "{{ custom_server_image | default(zabbix_server_image) }}:{{ custom_server_image_tag | default(zabbix_tag) }}"
                imagePullPolicy: "{{ zabbix_server_image_pull_policy | default(image_pull_policy) }}"
                ports:
                  - containerPort: 10051
                    name: active-data
                    protocol: TCP
                env:
                  - name: "DB_SERVER_HOST"
                    value: postgres-server
                  - name: "ZBX_SERVER_NAME"
                    value: zabbix-server
              - name: zabbix-snmptraps
                image: "{{ custom_server_image | default(zabbix_snmp_image) }}:{{ custom_server_image_tag |  default(zabbix_tag) }}"
                imagePullPolicy: "{{ zabbix_snmp_image_pull_policy | default(image_pull_policy) }}"
                ports:
                  - containerPort: 1162
                    name: snmp-trap
                    protocol: UDP
              - name: zabbix-agent
                image: "{{ custom_agent_image | default(zabbix_agent_image) }}:{{ custom_agent_image_tag | default(zabbix_tag) }}"
                imagePullPolicy: "{{ zabbix_agent_image_pull_policy | default(image_pull_policy) }}"
                env:
                  - name: ZBX_SERVER_HOST
                    value: 127.0.0.1
                ports:
                  - containerPort: 10051
                    name: agent-active
                    protocol: TCP
                  - containerPort: 10050
                    name: agent-passive
                    protocol: TCP

- name: Ensure zabbix-web deployment {{ state }} in namespace {{ instance }}
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        labels:
          app: zabbix
          tier: web
          release: "{{ release }}"
          domain: "{{ domain }}"
        name: zabbix-web
        namespace: "{{ instance }}"
      spec:
        replicas: "{{ zabbix_web_replicas }}"
        selector:
          matchLabels:
            app: zabbix
            tier: web
            release: "{{ release }}"
            domain: "{{ domain }}"
        template:
          metadata:
            labels:
              app: zabbix
              tier: web
              release: "{{ release }}"
              domain: "{{ domain }}"
          spec:
            containers:
              - name: zabbix-web
                image: "{{ custom_web_image | default(zabbix_web_image) }}:{{ custom_web_image_tag | default(zabbix_tag) }}"
                imagePullPolicy: "{{ web_image_pull_policy | default(image_pull_policy) }}"
                ports:
                  - containerPort: 80
                    name: http
                    protocol: TCP
                  - containerPort: 443
                    name: https
                    protocol: TCP
                env:
                  - name: ZBX_SERVER_HOST
                    value: zabbix-server
                  - name: DB_SERVER_HOST
                    value: postgres-server
                  - name: POSTGRES_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        key: POSTGRES_PASSWORD
                        name: zabbix-postgres
                        optional: false