---
# tasks file for zabbix
- name: Create {{ instance }} namespace
  k8s:
    name: "{{ instance }}"
    api_version: v1
    kind: Namespace
    state: "{{ state }}"

- name: Create {{ instance }} configmap
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ instance }}-configmap"
        namespace: "{{ instance }}"
      data:
        zabbix_server.conf: "{{ zabbix_server_conf}}"

- name: Create {{ instance }} postgres secret
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: zabbix-postgres
        namespace: "{{ instance }}"
      type: Opaque
      data:
        POSTGRES_PASSWORD: "{{ base64_postgres_password }}"

- name: Create {{ instance }} web services
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "zabbix-{{ instance }}-web"
        namespace: "{{ instance }}"
        labels:
          app: zabbix
      spec:
        type: NodePort
        selector:
          app: zabbix
        ports:
          - targetPort: https
            name: frontend-https
            port: 443
          - targetPort: http
            name: frontend-http
            port: 80

- name: Create {{ instance }} data services
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "zabbix-{{ instance }}-data"
        namespace: "{{ instance }}"
        labels:
          app: zabbix
      spec:
        type: NodePort
        selector:
          app: zabbix
        ports:
          - protocol: TCP
            targetPort: 10051
            name: active
            port: 10051
          - protocol: TCP
            targetPort: 10050
            name: passive
            port: 10050

- name: Create {{ instance }} zabbix statefulset
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        labels:
          app: zabbix
          release: "{{ release }}"
        name: "zabbix-{{ instance }}-pgsql"
        namespace: "{{ instance }}"
      spec:
        replicas: 1
        serviceName:
        selector:
          matchLabels:
            app: zabbix
            release: "{{ release }}"
        template:
          metadata:
            labels:
              app: zabbix
              release: "{{ release }}"
          spec:
            containers:
              - name: postgres-server
                imagePullPolicy: IfNotPresent
                image: "{{ database_image }}"
                ports:
                  - containerPort: 5432
                    name: 5432tcp5432
                    protocol: TCP
                env:
                  - name: POSTGRES_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        key: POSTGRES_PASSWORD
                        name: zabbix-postgres
                        optional: false
              - name: zabbix-server
                imagePullPolicy: IfNotPresent
                image: zabbix/zabbix-server-pgsql:alpine-trunk
                ports:
                  - containerPort: 10051
                    name: 10051tcp100510
                    protocol: TCP
                  - containerPort: 10050
                    name: 10050tcp10050
                    protocol: TCP
                env:
                  - name: "DB_SERVER_HOST"
                    value: "zabbix-{{ instance }}-pgsql-0"
              - name: zabbix-web
                imagePullPolicy: IfNotPresent
                image: zabbix/zabbix-web-nginx-pgsql:alpine-trunk
                ports:
                  - containerPort: 80
                    name: http
                    protocol: TCP
                  - containerPort: 443
                    name: https
                    protocol: TCP
                env:
                  - name: ZBX_SERVER_HOST
                    value: "zabbix-{{ instance }}-pgsql-0"
                  - name: DB_SERVER_HOST
                    value: "zabbix-{{ instance }}-pgsql-0"
                  - name: POSTGRES_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        key: POSTGRES_PASSWORD
                        name: zabbix-postgres
                        optional: false
              - name: zabbix-agent
                image: zabbix/zabbix-agent:alpine-trunk
                imagePullPolicy: Always
                env:
                  - name: ZBX_HOSTNAME
                    value: zabbix-server
                  - name: ZBX_PASSIVESERVERS
                    value: 127.0.0.1
