---
# tasks file for zabbix
- name: Ensure zabbix-postgres secret {{ state }} in namespace {{ instance }}
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: zabbix-postgres
        namespace: "{{ instance }}"
        labels:
          app: postgres
          tier: database
          release: "{{ release }}"
          domain: "{{ domain }}"
      type: Opaque
      data:
        POSTGRES_PASSWORD: "{{ base64_postgres_password }}"

- name: Ensure postgres-server service {{ state }} in namespace {{ instance }}
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: postgres-server
        namespace: "{{ instance }}"
        labels:
          app: postgres
          tier: database
          release: "{{ release }}"
          domain: "{{ domain }}"
      spec:
        selector:
          app: postgres
          tier: database
          release: "{{ release }}"
          domain: "{{ domain }}"
        ports:
          - targetPort: 5432
            name: database
            port: 5432
            protocol: TCP

- name: Ensure zabbix-server service {{ state }} in namespace {{ instance }}
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: zabbix-server
        namespace: "{{ instance }}"
        labels:
          app: zabbix
          tier: server
          release: "{{ release }}"
          domain: "{{ domain }}"
      spec:
        type: NodePort
        selector:
          app: zabbix
          tier: server
          release: "{{ release }}"
          domain: "{{ domain }}"
        ports:
          - targetPort: 10051
            name: active
            port: 10051
            protocol: TCP
          - targetPort: 10050
            name: agent-passive
            port: 10050
            protocol: TCP
          - targetPort: 1162
            port: 162
            name: snmp-trap
            protocol: UDP

- name: Ensure zabbix-web services {{ state }} in namespace {{ instance }}
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: zabbix-web
        namespace: "{{ instance }}"
        labels:
          app: zabbix
          tier: web
          release: "{{ release }}"
          domain: "{{ domain }}"
      spec:
        type: NodePort
        selector:
          app: zabbix
          tier: web
          release: "{{ release }}"
          domain: "{{ domain }}"
        ports:
          - targetPort: 8443
            name: frontend-https
            port: 443
          - targetPort: 8080
            name: frontend-http
            port: 80

- name: Ensure postgres-server statefulset {{ state }} in namespace {{ instance }}
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        labels:
          app: postgres
          tier: database
          release: "{{ release }}"
          domain: "{{ domain }}"
        name: postgres-server
        namespace: "{{ instance }}"
      spec:
        replicas: "{{ database_replicas }}"
        serviceName:
        selector:
          matchLabels:
            app: postgres
            tier: database
            release: "{{ release }}"
            domain: "{{ domain }}"
        updateStrategy:
          type: RollingUpdate
          rollingUpdate:
            partition: 1
        template:
          metadata:
            labels:
              app: postgres
              tier: database
              release: "{{ release }}"
              domain: "{{ domain }}"
          spec:
            containers:
              - name: postgres-server
                imagePullPolicy: "{{ database_image_pull_policy | default(image_pull_policy) }}"
                image: "{{ database_image }}:{{ database_image_tag }}"
                ports:
                  - containerPort: 5432
                    name: database
                    protocol: TCP
                env:
                  - name: POSTGRES_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        key: POSTGRES_PASSWORD
                        name: zabbix-postgres
                        optional: false
                  - name: PGDATA
                    value: /var/lib/postgresql/data
                volumeMounts:
                  - name: postgres-data
                    mountPath: /var/lib/postgresql/data
        volumeClaimTemplates:
          - metadata:
              name: postgres-data
              labels:
                app: postgres
                tier: database
                release: "{{ release }}"
                domain: "{{ domain }}"
            spec:
              accessModes:
                - ReadWriteMany
              selector:
                matchLabels:
                  app: postgres
                  tier: database
                  release: "{{ release }}"
                  domain: "{{ domain }}"
              resources:
                requests:
                  storage: "{{ database_claim_size }}"

- name: Ensure zabbix-server deployment {{ state }} in namespace {{ instance }}
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        labels:
          app: zabbix
          tier: server
          release: "{{ release }}"
          domain: "{{ domain }}"
        name: zabbix-server
        namespace: "{{ instance }}"
      spec:
        replicas: "{{ zabbix_server_replicas }}"
        selector:
          matchLabels:
            app: zabbix
            tier: server
            release: "{{ release }}"
            domain: "{{ domain }}"
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 30%
            maxUnavailable: 30%
        template:
          metadata:
            labels:
              app: zabbix
              tier: server
              release: "{{ release }}"
              domain: "{{ domain }}"
          spec:
            containers:
              - name: zabbix-server
                image: "{{ custom_server_image | default(zabbix_server_image) }}:{{ custom_server_image_tag | default(zabbix_tag) }}"
                imagePullPolicy: "{{ zabbix_server_image_pull_policy | default(image_pull_policy) }}"
                ports:
                  - containerPort: 10051
                    name: active-data
                    protocol: TCP
                env:
                  - name: "DB_SERVER_HOST"
                    value: postgres-server
                  - name: "ZBX_SERVER_NAME"
                    value: zabbix-server
              - name: zabbix-snmptraps
                image: "{{ custom_snmp_image | default(zabbix_snmp_image) }}:{{ custom_snmp_image_tag |  default(zabbix_tag) }}"
                imagePullPolicy: "{{ zabbix_snmp_image_pull_policy | default(image_pull_policy) }}"
                ports:
                  - containerPort: 1162
                    name: snmp-trap
                    protocol: UDP
              - name: zabbix-agent
                image: "{{ custom_agent_image | default(zabbix_agent_image) }}:{{ custom_agent_image_tag | default(zabbix_tag) }}"
                imagePullPolicy: "{{ zabbix_agent_image_pull_policy | default(image_pull_policy) }}"
                env:
                  - name: ZBX_SERVER_HOST
                    value: 127.0.0.1
                ports:
                  - containerPort: 10051
                    name: agent-active
                    protocol: TCP
                  - containerPort: 10050
                    name: agent-passive
                    protocol: TCP

- name: Ensure zabbix-web deployment {{ state }} in namespace {{ instance }}
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        labels:
          app: zabbix
          tier: web
          release: "{{ release }}"
          domain: "{{ domain }}"
        name: zabbix-web
        namespace: "{{ instance }}"
      spec:
        replicas: "{{ zabbix_web_replicas }}"
        selector:
          matchLabels:
            app: zabbix
            tier: web
            release: "{{ release }}"
            domain: "{{ domain }}"
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 30%
            maxUnavailable: 30%
        template:
          metadata:
            labels:
              app: zabbix
              tier: web
              release: "{{ release }}"
              domain: "{{ domain }}"
          spec:
            containers:
              - name: zabbix-web
                image: "{{ custom_web_image | default(zabbix_web_image) }}:{{ custom_web_image_tag | default(zabbix_tag) }}"
                imagePullPolicy: "{{ web_image_pull_policy | default(image_pull_policy) }}"
                ports:
                  - containerPort: 80
                    name: http
                    protocol: TCP
                  - containerPort: 443
                    name: https
                    protocol: TCP
                env:
                  - name: ZBX_SERVER_HOST
                    value: zabbix-server
                  - name: DB_SERVER_HOST
                    value: postgres-server
                  - name: POSTGRES_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        key: POSTGRES_PASSWORD
                        name: zabbix-postgres
                        optional: false

- name: Ensure stable repo added
  helm_repository:
    repo_name: stable
    repo_state: "{{ state }}"
    repo_url: "https://kubernetes-charts.storage.googleapis.com"
  when: cluster_monitoring

- name: Ensure node exporter installed
  helm:
    chart_ref: stable/prometheus-node-exporter
    release_name: "{{ domain }}"
    release_state: "{{ state }}"
    release_namespace: "{{ instance }}"
  when: cluster_monitoring

- name: Get Server deployment
  k8s_info:
    kind: Deployment
    label_selectors:
      - app = zabbix
      - tier = server
  register: server_deployment
  when:
    - cluster_monitoring

- name: Get cluster Nodes
  k8s_info:
    kind: Node
  register: cluster_nodes
  when:
    - cluster_monitoring

- name: Set node_list fact
  set_fact:
    node_list: "{{ nodes|default([]) + [ item.status.addresses ] }}"
  loop: "{{ cluster_nodes.resources }}"
  no_log: true

- name: Set hosts fact
  set_fact:
    hosts: "{{ item.address | default('')  }}"
  loop: "{{ node_list | flatten }}"
  when: item.type == 'InternalIP'
  no_log: true

- name: Run monitoring config job
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: batch/v1
      kind: Job
      metadata:
        labels:
          app: zabbix
          tier: job
          release: "{{ release }}"
          domain: "{{ domain }}"
        name: zabbix-configure-job
        namespace: "{{ instance }}"
      spec:
        template:
          metadata:
            name: cluster-config
          spec:
            containers:
              - name: cluster-config-job
                image: "{{ cluster_config_job_image }}:{{ cluster_config_job_image_tag }}"
                args:
                  - "-user"
                  - "{{ zabbix_frontend_user }}"
                  - "-passwd"
                  - "{{ zabbix_frontend_passwd }}"
                  - "-nodes"
                  - "{{ hosts }}"
            restartPolicy: OnFailure
        backoffLimit: 4
  when:
    - cluster_monitoring
    - server_deployment.resources[0] is not undefined
    - server_deployment.resources[0].status.availableReplicas