---
# defaults file for zabbix
instance: zabbix
state: present
release: 0.0.1
domain: minikube
zabbix_server_replicas: 2
zabbix_web_replicas: 2
zabbix_server_image: zabbix/zabbix-server-pgsql
zabbix_snmp_image: zabbix/zabbix-snmptraps
zabbix_agent_image: zabbix/zabbix-agent
zabbix_web_image: zabbix/zabbix-web-nginx-pgsql
zabbix_tag: alpine-trunk
image_pull_policy: IfNotPresent
database_image: registry.gitlab.com/frenchtoasters/zabbix-operator/zabbix-database-postgres
database_image_tag: latest
database_claim_size: 700M
database_replicas: 1
zabbix_frontend_user: Admin
zabbix_frontend_passwd: emFiYml4
base64_postgres_password: emFiYml4
cluster_config_job_image: registry.gitlab.com/frenchtoasters/zabbix-operator/zabbix-config-job
cluster_config_job_image_tag: latest
cluster_monitoring: true
database_monitoring: true