apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: zabbixes.monitoring.frenchtoastman.com
spec:
  group: monitoring.frenchtoastman.com
  names:
    kind: Zabbix
    listKind: ZabbixList
    plural: zabbixes
    singular: zabbix
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
