apiVersion: monitoring.frenchtoastman.com/v1alpha1
kind: Zabbix
metadata:
  name: example-zabbix
spec:
  state: present
  release: 0.0.1
  domain: minikube
  zabbix_server_replicas: 2
  zabbix_web_replicas: 2
  zabbix_server_image: zabbix/zabbix-server-pgsql
  zabbix_server_image_pull_policy: Always
  zabbix_snmp_image: zabbix/zabbix-snmptraps
  zabbix_agent_image: zabbix/zabbix-agent
  zabbix_web_image: zabbix/zabbix-web-nginx-pgsql
  zabbix_tag: alpine-4.0-latest
  image_pull_policy: IfNotPresent
  database_image: registry.gitlab.com/frenchtoasters/zabbix-operator/zabbix-database-postgres
  database_image_tag: 4
  database_claim_size: 700M
  base64_postgres_password: emFiYml4
  cluster_monitoring: true