apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "zabbix-operator-chart.serviceAccountName" . }}
  labels:
    {{- include "zabbix-operator-chart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "zabbix-operator-chart.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "zabbix-operator-chart.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
