---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zabbix-operator
  template:
    metadata:
      labels:
        name: zabbix-operator
    spec:
      serviceAccountName: zabbix-operator
      containers:
        - name: zabbix-operator
          # Replace this with the built image name
          image: registry.gitlab.com/frenchtoasters/zabbix-operator/zabbix-operator:v0.1.1
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "zabbix-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
      volumes:
        - name: runner
          emptyDir: {}
