kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zabbix-operator
subjects:
- kind: ServiceAccount
  name: zabbix-operator
  namespace: zabbix
roleRef:
  kind: ClusterRole
  name: zabbix-operator
  apiGroup: rbac.authorization.k8s.io
